// frontend/src/components/common/AppFooter.vue
<script setup lang="ts">
import { css } from 'styled-system/css'
</script>

<template>
  <footer :class="css({ bg: 'green.500', color: 'white', px: '8', py: '12', pb: '8' })">
    <div :class="css({ maxW: '1200px', mx: 'auto' })">
      <div
        :class="
          css({
            display: 'flex',
            justifyContent: 'center',
            gap: { base: '8', md: '12' },
            mb: '8',
            flexWrap: 'wrap',
          })
        "
      >
        <div :class="css({ display: 'flex', flexDirection: 'column', gap: '4' })">
          <h3 :class="css({ fontSize: '1.125rem', fontWeight: '600', mb: '2' })">About</h3>
          <a
            href="/about"
            :class="
              css({
                color: 'white',
                textDecoration: 'none',
                fontSize: '0.875rem',
                opacity: 0.9,
                transition: 'opacity 0.2s',
                _hover: { opacity: 1 },
              })
            "
            >About Gaji</a
          >
          <!--<a
            href="/team"
            :class="
              css({
                color: 'white',
                textDecoration: 'none',
                fontSize: '0.875rem',
                opacity: 0.9,
                transition: 'opacity 0.2s',
                _hover: { opacity: 1 },
              })
            "
            >Our Team</a
          >-->
        </div>

        <!--<div :class="css({ display: 'flex', flexDirection: 'column', gap: '4' })">
          <h3 :class="css({ fontSize: '1.125rem', fontWeight: '600', mb: '2' })">Support</h3>
          <a
            href="/help"
            :class="
              css({
                color: 'white',
                textDecoration: 'none',
                fontSize: '0.875rem',
                opacity: 0.9,
                transition: 'opacity 0.2s',
                _hover: { opacity: 1 },
              })
            "
            >Help & Support</a
          >
          <a
            href="/contact"
            :class="
              css({
                color: 'white',
                textDecoration: 'none',
                fontSize: '0.875rem',
                opacity: 0.9,
                transition: 'opacity 0.2s',
                _hover: { opacity: 1 },
              })
            "
            >Contact Us</a
          >
          <a
            href="/faq"
            :class="
              css({
                color: 'white',
                textDecoration: 'none',
                fontSize: '0.875rem',
                opacity: 0.9,
                transition: 'opacity 0.2s',
                _hover: { opacity: 1 },
              })
            "
            >FAQ</a
          >
        </div>

        <div :class="css({ display: 'flex', flexDirection: 'column', gap: '4' })">
          <h3 :class="css({ fontSize: '1.125rem', fontWeight: '600', mb: '2' })">Legal</h3>
          <a
            href="/terms"
            :class="
              css({
                color: 'white',
                textDecoration: 'none',
                fontSize: '0.875rem',
                opacity: 0.9,
                transition: 'opacity 0.2s',
                _hover: { opacity: 1 },
              })
            "
            >Terms of Service</a
          >
          <a
            href="/privacy"
            :class="
              css({
                color: 'white',
                textDecoration: 'none',
                fontSize: '0.875rem',
                opacity: 0.9,
                transition: 'opacity 0.2s',
                _hover: { opacity: 1 },
              })
            "
            >Privacy Policy</a
          >
          <a
            href="/cookies"
            :class="
              css({
                color: 'white',
                textDecoration: 'none',
                fontSize: '0.875rem',
                opacity: 0.9,
                transition: 'opacity 0.2s',
                _hover: { opacity: 1 },
              })
            "
            >Cookie Policy</a
          >
        </div>-->

        <div :class="css({ display: 'flex', flexDirection: 'column', gap: '4' })">
          <h3 :class="css({ fontSize: '1.125rem', fontWeight: '600', mb: '2' })">Connect</h3>
          <div :class="css({ display: 'flex', gap: '4' })">
            <a
              href="https://github.com"
              target="_blank"
              rel="noopener noreferrer"
              :class="
                css({
                  fontSize: '1.5rem',
                  color: 'white',
                  textDecoration: 'none',
                  opacity: 0.9,
                  transition: 'opacity 0.2s',
                  _hover: { opacity: 1 },
                })
              "
              aria-label="GitHub"
            >
              <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor">
                <path
                  d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"
                />
              </svg>
            </a>
            <a
              href="https://discord.com"
              target="_blank"
              rel="noopener noreferrer"
              :class="
                css({
                  fontSize: '1.5rem',
                  color: 'white',
                  textDecoration: 'none',
                  opacity: 0.9,
                  transition: 'opacity 0.2s',
                  _hover: { opacity: 1 },
                })
              "
              aria-label="Discord"
            >
              <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor">
                <path
                  d="M20.317 4.37a19.791 19.791 0 0 0-4.885-1.515.074.074 0 0 0-.079.037c-.21.375-.444.864-.608 1.25a18.27 18.27 0 0 0-5.487 0 12.64 12.64 0 0 0-.617-1.25.077.077 0 0 0-.079-.037A19.736 19.736 0 0 0 3.677 4.37a.07.07 0 0 0-.032.027C.533 9.046-.32 13.58.099 18.057a.082.082 0 0 0 .031.057 19.9 19.9 0 0 0 5.993 3.03.078.078 0 0 0 .084-.028 14.09 14.09 0 0 0 1.226-1.994.076.076 0 0 0-.041-.106 13.107 13.107 0 0 1-1.872-.892.077.077 0 0 1-.008-.128 10.2 10.2 0 0 0 .372-.292.074.074 0 0 1 .077-.01c3.928 1.793 8.18 1.793 12.062 0a.074.074 0 0 1 .078.01c.12.098.246.198.373.292a.077.077 0 0 1-.006.127 12.299 12.299 0 0 1-1.873.892.077.077 0 0 0-.041.107c.36.698.772 1.362 1.225 1.993a.076.076 0 0 0 .084.028 19.839 19.839 0 0 0 6.002-3.03.077.077 0 0 0 .032-.054c.5-5.177-.838-9.674-3.549-13.66a.061.061 0 0 0-.031-.03zM8.02 15.33c-1.183 0-2.157-1.085-2.157-2.419 0-1.333.956-2.419 2.157-2.419 1.21 0 2.176 1.096 2.157 2.42 0 1.333-.956 2.418-2.157 2.418zm7.975 0c-1.183 0-2.157-1.085-2.157-2.419 0-1.333.955-2.419 2.157-2.419 1.21 0 2.176 1.096 2.157 2.42 0 1.333-.946 2.418-2.157 2.418z"
                />
              </svg>
            </a>
          </div>
        </div>
      </div>

      <div :class="css({ borderTop: '1px solid', borderColor: 'whiteAlpha.300', my: '8' })" />

      <div :class="css({ textAlign: 'center', fontSize: '0.875rem', opacity: 0.8 })">
        © 2025 Gaji. All rights reserved.<br />
        v1.0.0
      </div>
    </div>
  </footer>
</template>

// src/domains/shell/components/AppFooter.tsx
export function AppFooter() {
  return (
    <footer className='app-footer'>
      <div className='app-footer__inner'>
        <div className='app-footer__left'>
          <span>© 2026 Gaji</span>
          <a href='/about'>About</a>
        </div>

        <div className='app-footer__social'>
          <a href='https://github.com' target='_blank' rel='noreferrer noopener' aria-label='GitHub'>
            <svg viewBox='0 0 24 24' aria-hidden='true'>
              <path d='M12 0a12 12 0 0 0-3.79 23.39c.6.11.82-.26.82-.58v-2.02c-3.34.73-4.04-1.41-4.04-1.41-.54-1.39-1.33-1.76-1.33-1.76-1.09-.74.08-.73.08-.73 1.2.09 1.84 1.24 1.84 1.24 1.07 1.83 2.8 1.3 3.48 1 .11-.78.42-1.31.76-1.61-2.66-.3-5.46-1.33-5.46-5.93 0-1.31.47-2.38 1.23-3.22-.12-.3-.53-1.52.12-3.17 0 0 1.01-.32 3.3 1.23a11.44 11.44 0 0 1 6.01 0c2.29-1.55 3.29-1.23 3.29-1.23.66 1.65.25 2.87.12 3.17.77.84 1.24 1.91 1.24 3.22 0 4.61-2.81 5.62-5.48 5.92.43.37.82 1.1.82 2.22v3.29c0 .32.2.7.81.58A12 12 0 0 0 12 0Z' />
            </svg>
          </a>

          <a href='https://discord.com' target='_blank' rel='noreferrer noopener' aria-label='Discord'>
            <svg viewBox='0 0 24 24' aria-hidden='true'>
              <path d='M20.32 4.37A19.8 19.8 0 0 0 15.43 2.85a.08.08 0 0 0-.08.04c-.2.37-.43.86-.6 1.25a18.3 18.3 0 0 0-5.49 0 12.7 12.7 0 0 0-.62-1.25.08.08 0 0 0-.08-.04A19.8 19.8 0 0 0 3.68 4.37a.06.06 0 0 0-.03.03C.53 9.05-.32 13.58.1 18.06a.08.08 0 0 0 .03.06 19.9 19.9 0 0 0 5.99 3.03.08.08 0 0 0 .09-.03c.45-.63.86-1.3 1.22-1.99a.08.08 0 0 0-.04-.11 13.2 13.2 0 0 1-1.87-.89.08.08 0 0 1-.01-.12c.12-.1.25-.2.37-.29a.08.08 0 0 1 .08-.01c3.93 1.8 8.18 1.8 12.06 0a.08.08 0 0 1 .08.01c.12.1.25.2.37.3a.08.08 0 0 1-.01.12c-.6.35-1.22.65-1.87.88a.08.08 0 0 0-.04.11c.36.69.77 1.36 1.22 1.99a.08.08 0 0 0 .09.03 19.8 19.8 0 0 0 6-3.03.08.08 0 0 0 .03-.05c.5-5.18-.84-9.68-3.55-13.66a.06.06 0 0 0-.03-.03ZM8.02 15.33c-1.18 0-2.16-1.09-2.16-2.42 0-1.34.96-2.42 2.16-2.42 1.2 0 2.18 1.1 2.16 2.42 0 1.33-.96 2.42-2.16 2.42Zm7.97 0c-1.18 0-2.15-1.09-2.15-2.42 0-1.34.95-2.42 2.15-2.42 1.21 0 2.18 1.1 2.16 2.42 0 1.33-.95 2.42-2.16 2.42Z' />
            </svg>
          </a>
        </div>
      </div>
    </footer>
  );
}
